go s3 bucket

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -110,7 +110,7 @@ jobs:
           echo "✅ Final Reports Structure:"
           tree reports-${{ github.sha }} || ls -R reports-${{ github.sha }}
 
-      - name: Upload to S3
+      - name: Upload to S3 
         uses: jakejarvis/s3-sync-action@master
         with:
           args: --follow-symlinks --delete
@@ -123,66 +123,66 @@ jobs:
           DEST_DIR: reports/${{ github.sha }}
         
                                
-  docker:
-      name: Docker Image CI
-      runs-on: ubuntu-latest
-      needs: [unit-testing, code-coverage]
-      steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+  # docker:
+  #     name: Docker Image CI
+  #     runs-on: ubuntu-latest
+  #     needs: [unit-testing, code-coverage]
+  #     steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v3.5.0
-        with:
-          username: ${{ vars.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v3.5.0
+  #       with:
+  #         username: ${{ vars.DOCKER_HUB_USERNAME }}
+  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-      - name: Build and Push Docker Image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: true
-          tags: ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-world:${{ github.sha }}
+  #     - name: Build and Push Docker Image
+  #       uses: docker/build-push-action@v4
+  #       with:
+  #         context: .
+  #         push: true
+  #         tags: ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-world:${{ github.sha }}
         
-      - name: Docker Image Test
-        env:
-          MONGO_URI: ${{ secrets.MONGO_URI }}
-          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
-          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
-        run: |
-          echo "🚀 Starting container for testing..."
+  #     - name: Docker Image Test
+  #       env:
+  #         MONGO_URI: ${{ secrets.MONGO_URI }}
+  #         MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
+  #         MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
+  #       run: |
+  #         echo "🚀 Starting container for testing..."
       
-          docker run --name solar-system-app -d \
-            -p 3000:3000 \
-            -e MONGO_URI=$MONGO_URI \
-            -e MONGO_USERNAME=$MONGO_USERNAME \
-            -e MONGO_PASSWORD=$MONGO_PASSWORD \
-            ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-world:${{ github.sha }}
+  #         docker run --name solar-system-app -d \
+  #           -p 3000:3000 \
+  #           -e MONGO_URI=$MONGO_URI \
+  #           -e MONGO_USERNAME=$MONGO_USERNAME \
+  #           -e MONGO_PASSWORD=$MONGO_PASSWORD \
+  #           ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-world:${{ github.sha }}
       
-          echo "⏳ Waiting for app to be healthy..."
-          for i in {1..10}; do
-            if curl -s http://127.0.0.1:3000/live | grep -q "live"; then
-              echo "✅ App is healthy and responded correctly"
-              break
-            fi
-            echo "Waiting... ($i/10)"
-            sleep 3
-          done
+  #         echo "⏳ Waiting for app to be healthy..."
+  #         for i in {1..10}; do
+  #           if curl -s http://127.0.0.1:3000/live | grep -q "live"; then
+  #             echo "✅ App is healthy and responded correctly"
+  #             break
+  #           fi
+  #           echo "Waiting... ($i/10)"
+  #           sleep 3
+  #         done
       
-          # لو التطبيق مفعلش نفسه
-          if ! curl -s http://127.0.0.1:3000/live | grep -q "live"; then
-            echo "❌ App failed health check"
-            docker logs solar-system-app
-            exit 1
-          fi
+  #         # لو التطبيق مفعلش نفسه
+  #         if ! curl -s http://127.0.0.1:3000/live | grep -q "live"; then
+  #           echo "❌ App failed health check"
+  #           docker logs solar-system-app
+  #           exit 1
+  #         fi
       
-          echo "🧹 Cleaning up..."
-          echo "----------------------------------------------"
-          echo "🧹 stop solar-system-app..."
-          docker stop solar-system-app
-          echo "🧹 remove solar-system-app..."
-          docker rm solar-system-app
+  #         echo "🧹 Cleaning up..."
+  #         echo "----------------------------------------------"
+  #         echo "🧹 stop solar-system-app..."
+  #         docker stop solar-system-app
+  #         echo "🧹 remove solar-system-app..."
+  #         docker rm solar-system-app
       
