add docker s

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -13,40 +13,40 @@ env:
   MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
   MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
 jobs:
-    unit-testing:
-        name: Unit Testing
-        runs-on: ubuntu-latest
-        steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v4
+  unit-testing:
+      name: Unit Testing
+      runs-on: ubuntu-latest
+      steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-        - name: Setup NodeJS Version
-          uses: actions/setup-node@v3
-          with:
-            node-version: 18
+      - name: Setup NodeJS Version
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
 
-        - name: Cache NPM dependencies
-          uses: actions/cache@v3
-          with:
-            path: node_modules
-            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
-    
-        - name: Install Dependencies
-          run: npm install
-    
-        - name: Unit Testing
-          run: npm test
-          
-        - name: Archive Test Result
-          if: always()
-          uses: actions/upload-artifact@v4
-          with:
-            name: Mocha-Test-Result
-            path: test-results.xml
-
-        
+      - name: Cache NPM dependencies
+        uses: actions/cache@v3
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
   
-    code-coverage:
+      - name: Install Dependencies
+        run: npm install
+  
+      - name: Unit Testing
+        run: npm test
+        
+      - name: Archive Test Result
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: Mocha-Test-Result
+          path: test-results.xml
+
+      
+
+  code-coverage:
             name: Coverage Report
             runs-on: ubuntu-latest
             needs: unit-testing
@@ -77,3 +77,64 @@ jobs:
               with:
                 name: Coverage-Report
                 path: coverage/
+
+  docker:
+      name: Docker Image CI
+      runs-on: ubuntu-latest
+      needs: [unit-testing, code-coverage]
+      steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v3.5.0
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+
+      - name: Build and Push Docker Image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          push: true
+          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/solar-system-world:${{ github.sha }}
+        
+      - name: Docker Image Test
+        env:
+          MONGO_URI: ${{ secrets.MONGO_URI }}
+          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
+          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
+        run: |
+          echo "🚀 Starting container for testing..."
+      
+          docker run --name solar-system-app -d \
+            -p 3000:3000 \
+            -e MONGO_URI=$MONGO_URI \
+            -e MONGO_USERNAME=$MONGO_USERNAME \
+            -e MONGO_PASSWORD=$MONGO_PASSWORD \
+            ${{ secrets.DOCKER_HUB_USERNAME }}/solar-system-world:${{ github.sha }}
+      
+          echo "⏳ Waiting for app to be healthy..."
+          for i in {1..10}; do
+            if curl -s http://127.0.0.1:3000/live | grep -q "live"; then
+              echo "✅ App is healthy and responded correctly"
+              break
+            fi
+            echo "Waiting... ($i/10)"
+            sleep 3
+          done
+      
+          # لو التطبيق مفعلش نفسه
+          if ! curl -s http://127.0.0.1:3000/live | grep -q "live"; then
+            echo "❌ App failed health check"
+            docker logs solar-system-app
+            exit 1
+          fi
+      
+          echo "🧹 Cleaning up..."
+          docker stop solar-system-app
+          docker rm solar-system-app
+      
