update

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -15,114 +15,114 @@ env:
 
 jobs:
   
-  unit-testing:
-    name: Unit Testing
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+  # unit-testing:
+  #   name: Unit Testing
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
 
-      - name: Setup NodeJS Version
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
+  #     - name: Setup NodeJS Version
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 18
 
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: node_modules
-          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
+  #     - name: Cache NPM dependencies
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: node_modules
+  #         key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
   
-      - name: Install Dependencies
-        run: npm install
+  #     - name: Install Dependencies
+  #       run: npm install
   
-      - name: Unit Testing
-        run: npm test
+  #     - name: Unit Testing
+  #       run: npm test
         
-      - name: Archive Test Result
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: Mocha-Test-Result
-          path: test-results.xml   # ملف واحد بس
+  #     - name: Archive Test Result
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Mocha-Test-Result
+  #         path: test-results.xml   # ملف واحد بس
 
-  code-coverage:
-    name: Coverage Report
-    runs-on: ubuntu-latest
-    needs: unit-testing
-    if: always()
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+  # code-coverage:
+  #   name: Coverage Report
+  #   runs-on: ubuntu-latest
+  #   needs: unit-testing
+  #   if: always()
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
 
-      - name: Setup NodeJS Version
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
+  #     - name: Setup NodeJS Version
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 18
 
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: node_modules
-          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
+  #     - name: Cache NPM dependencies
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: node_modules
+  #         key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
         
-      - name: Install Dependencies
-        run: npm install
+  #     - name: Install Dependencies
+  #       run: npm install
 
-      - name: Generate Coverage Report
-        run: npm run coverage || echo "⚠️ Coverage generation failed, continuing anyway"
+  #     - name: Generate Coverage Report
+  #       run: npm run coverage || echo "⚠️ Coverage generation failed, continuing anyway"
       
-      - name: Upload Coverage Report
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: Code-Coverage-Result
-          path: coverage/
-          if-no-files-found: ignore
+  #     - name: Upload Coverage Report
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Code-Coverage-Result
+  #         path: coverage/
+  #         if-no-files-found: ignore
 
-  reports-s3:
-    name: Upload Reports to S3
-    runs-on: ubuntu-latest
-    needs: [unit-testing, code-coverage]
-    if: always()
-    steps:
-      - name: Download Mocha Test Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: Mocha-Test-Result
-          path: ./unit-testing
+  # reports-s3:
+  #   name: Upload Reports to S3
+  #   runs-on: ubuntu-latest
+  #   needs: [unit-testing, code-coverage]
+  #   if: always()
+  #   steps:
+  #     - name: Download Mocha Test Artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: Mocha-Test-Result
+  #         path: ./unit-testing
 
-      - name: Download Code Coverage Artifact  
-        uses: actions/download-artifact@v4
-        with:
-          name: Code-Coverage-Result
-          path: ./code-coverage
+  #     - name: Download Code Coverage Artifact  
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: Code-Coverage-Result
+  #         path: ./code-coverage
 
-      - name: Organize Reports into Commit Folder
-        run: |
-          mkdir -p reports-${{ github.sha }}
-          mv unit-testing reports-${{ github.sha }}/ || true
-          mv code-coverage reports-${{ github.sha }}/ || true
+  #     - name: Organize Reports into Commit Folder
+  #       run: |
+  #         mkdir -p reports-${{ github.sha }}
+  #         mv unit-testing reports-${{ github.sha }}/ || true
+  #         mv code-coverage reports-${{ github.sha }}/ || true
 
-          echo "✅ Final Reports Structure:"
-          tree reports-${{ github.sha }} || ls -R reports-${{ github.sha }}
+  #         echo "✅ Final Reports Structure:"
+  #         tree reports-${{ github.sha }} || ls -R reports-${{ github.sha }}
 
-      - name: Upload to S3 
-        uses: jakejarvis/s3-sync-action@master
-        with:
-          args: --follow-symlinks --delete
-        env:
-          AWS_S3_BUCKET: reports-bucket-shady-yasser
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
-          AWS_REGION: 'us-east-1'
-          SOURCE_DIR: reports-${{ github.sha }}
-          DEST_DIR: reports/${{ github.sha }}
+  #     - name: Upload to S3 
+  #       uses: jakejarvis/s3-sync-action@master
+  #       with:
+  #         args: --follow-symlinks --delete
+  #       env:
+  #         AWS_S3_BUCKET: reports-bucket-shady-yasser
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
+  #         AWS_REGION: 'us-east-1'
+  #         SOURCE_DIR: reports-${{ github.sha }}
+  #         DEST_DIR: reports/${{ github.sha }}
                                
   docker:
       name: Docker Image CI
       runs-on: ubuntu-latest
-      needs: [unit-testing, code-coverage]
+      # needs: [unit-testing, code-coverage]
       steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
